// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var STOREFRONT_URL = "https://iyeyb5-2r.myshopify.com/api/2024-10/graphql.json";
var STOREFRONT_TOKEN_FALLBACK = "e9c7c1f8e6a4d8b5c2f1a3e7b9d4c6f2";
var QUERY = (
  /* GraphQL */
  `
  query ListProducts($first: Int!) {
    products(first: $first) {
      edges {
        node {
          id
          handle
          title
          description
          priceRange { minVariantPrice { amount currencyCode } }
        }
      }
    }
  }
`
);
var list_products_default = defineTool({
  name: "list_products",
  title: "List cakes and sweets",
  description: "Browse the Sweet Layers product catalog (handle, title, description, price).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max products to return (1\u201350).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const token = globalThis.process?.env?.SHOPIFY_STOREFRONT_ACCESS_TOKEN ?? STOREFRONT_TOKEN_FALLBACK;
    const res = await fetch(STOREFRONT_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": token
      },
      body: JSON.stringify({ query: QUERY, variables: { first: limit } })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Shopify error: ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const products = (json.data?.products?.edges ?? []).map((e) => ({
      handle: e.node.handle,
      title: e.node.title,
      description: e.node.description,
      price: `${e.node.priceRange.minVariantPrice.amount} ${e.node.priceRange.minVariantPrice.currencyCode}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var STOREFRONT_URL2 = "https://iyeyb5-2r.myshopify.com/api/2024-10/graphql.json";
var STOREFRONT_TOKEN_FALLBACK2 = "e9c7c1f8e6a4d8b5c2f1a3e7b9d4c6f2";
var QUERY2 = (
  /* GraphQL */
  `
  query GetProduct($handle: String!) {
    productByHandle(handle: $handle) {
      id
      handle
      title
      description
      priceRange { minVariantPrice { amount currencyCode } }
      variants(first: 20) {
        edges { node { id title availableForSale price { amount currencyCode } } }
      }
    }
  }
`
);
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch a single product by its Shopify handle, including variants and pricing.",
  inputSchema: {
    handle: z2.string().min(1).describe("The Shopify product handle, e.g. 'the-minimalist'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ handle }) => {
    const token = globalThis.process?.env?.SHOPIFY_STOREFRONT_ACCESS_TOKEN ?? STOREFRONT_TOKEN_FALLBACK2;
    const res = await fetch(STOREFRONT_URL2, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": token
      },
      body: JSON.stringify({ query: QUERY2, variables: { handle } })
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Shopify error: ${res.status}` }], isError: true };
    }
    const json = await res.json();
    const product = json.data?.productByHandle;
    if (!product) {
      return { content: [{ type: "text", text: `No product found for handle: ${handle}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool3({
  name: "whoami",
  title: "Who am I",
  description: "Returns the signed-in Sweet Layers user identity for the current MCP session.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const identity = { userId: ctx.getUserId(), email: ctx.getUserEmail(), clientId: ctx.getClientId() };
    return {
      content: [{ type: "text", text: JSON.stringify(identity, null, 2) }],
      structuredContent: identity
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ogmpjsuxzkvwszoqeqjb";
var mcp_default = defineMcp({
  name: "sweet-layers-mcp",
  title: "Sweet Layers",
  version: "0.1.0",
  instructions: "Tools for the Sweet Layers luxury cake atelier. Use `list_products` to browse the catalog, `get_product` to fetch details by handle, and `whoami` to verify identity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_product_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
